server:
  port: 8092
spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:mysql:///changyou?useUnicode=true&characterEncoding=utf8
    username: root
    password: root

  rabbitmq:
    host: 182.92.2.24
    virtual-host: /changyou
    username: changyou
    password: changyou
    port: 5672
    publisher-confirms: true
    #消息发送失败的回调函数
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        #并发消费者初始化值
        concurrency: 10
        #并发消费者的最大值
        max-concurrency: 20
  redis:
    host: 39.105.34.127

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 #心跳时间
    lease-expiration-duration-in-seconds: 15 #过期时间
mybatis:
  type-aliases-package: cn.changyou.comment.pojo
changyou:
  jwt:
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    cookieName: CY_TOKEN