server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 39.105.34.127
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
changyou:
  jwt:
    pubKeyPath: D:\\temp\\rsa\\rsa.pub # 公钥地址
    cookieName: CY_TOKEN